vim.keymap.set("n", "<leader>ob", "<cmd> GoBuild<CR>")
vim.keymap.set("n", "<leader>ol", "<cmd> GoInstall<CR>")
vim.keymap.set("n", "<leader>ot", "<cmd> GoTest<CR>")
vim.keymap.set("n", "<leader>oy", "<cmd> GoTestFunc<CR>")
vim.keymap.set("n", "<leader>ou", "<cmd> GoDebugStart<CR>")
vim.keymap.set("n", "<leader>od", "<cmd> GoDef<CR>")
vim.keymap.set("n", "<leader>oi", function()
    vim.cmd("GoImport " .. vim.fn.input("Import > "))
end)
vim.keymap.set("n", "<leader>op", function()
    vim.cmd("GoDrop " .. vim.fn.input("Drop > "))
end)
vim.keymap.set("n", "<leader>or", "<cmd> GoRename<CR>")
vim.keymap.set("n", "<leader>oc", "<cmd> GoCoverage<CR>")
