return {
    -- "folke/noice.nvim",
    -- event = "VeryLazy",
    -- opts = {},
    -- dependencies = {
    --     "MunifTanjim/nui.nvim",
    --     "rcarriga/nvim-notify",
    -- },
    -- config = function()
    --     require("noice").setup({
    --         {
    --             lsp = {
    --                 hover = {
    --                     enabled = false,
    --                     opts = {}, -- merged with defaults from documentation
    --                 },
    --                 signature = {
    --                     enabled = false,
    --                     opts = {}, -- merged with defaults from documentation
    --                 },
    --             },
    --         }
    --     })
    -- end
}
